name: Package Version Tags
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/bannerlord-unofficial-modding-community/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Install dependencies
      run: dotnet restore
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Build & Pack Library
      run: dotnet pack -c Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Build & Pack Tool
      run: dotnet pack -c Release -p:IsTool=true
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Push
      run: dotnet nuget push 'ReferenceAssemblyGenerator/nuget/*.nupkg' -s Source -k "${{secrets.GITHUB_TOKEN}}" --skip-duplicate
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
